flags:
  aeson:
    old-locale: true
extra-package-dbs: []
packages:
- '.'
extra-deps:
- abcnotation-1.9.0
- aeson-0.11.0.0
- applicative-numbers-0.1.3
- attoparsec-0.13.0.1
- average-0.6.1
- base-orphans-0.3.3
- bifunctors-5.2
- data-interval-1.2.0
- extended-reals-0.2.1.0
- fail-4.9.0.0
- free-4.12.4
- happstack-lite-7.3.6
- hspec-2.2.2
- hspec-core-2.2.2
- hspec-discover-2.2.2
- hspec-expectations-0.7.2
- kan-extensions-5.0.1
- lens-4.13.2
- lilypond-1.9.0
- monadplus-1.4.2
- mtl-2.2.1
- music-articulation-1.9.0
- music-dynamics-1.9.0
- music-dynamics-literal-1.9.0
- music-parts-1.9.0
- music-pitch-1.9.0
- music-pitch-literal-1.9.0
- music-preludes-1.9.0
- music-score-1.9.0
- music-suite-1.9.0
- musicxml2-1.9.0
- positive-0.4.1
- prettify-1.0
- primitive-0.6.1.0
- profunctors-5.1.2
- reflection-2.1.2
- reverse-apply-2.0.1
- roman-numerals-0.5.1.5
- semigroupoids-5.0.1
- transformers-0.4.3.0
- transformers-compat-0.4.0.4
- ty-0.1.6
- type-unary-0.2.21
- vector-0.11.0.0
- vector-space-0.10.3
resolver: lts-2.22
