flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- attoparsec-0.13.0.1
- distributed-process-0.6.0
- distributed-process-simplelocalnet-0.2.3.2
- distributed-static-0.3.4.0
- happstack-lite-7.3.6
- hmt-0.15
- hosc-0.14.1
- hspec-2.2.2
- hspec-core-2.2.2
- hspec-discover-2.2.2
- hspec-expectations-0.7.2
- mersenne-random-pure64-0.2.0.4
- multiset-comb-0.2.4
- network-transport-tcp-0.5.1
- permutation-0.5.0.5
- rank1dynamic-0.3.2.0
- text-1.2.2.0
- tidal-0.6
- vector-0.11.0.0
resolver: lts-3.22
