flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- abcnotation-1.9.0
- aeson-0.11.0.0
- applicative-numbers-0.1.3
- average-0.6.1
- base-orphans-0.3.3
- data-interval-1.2.0
- extended-reals-0.2.1.0
- fail-4.9.0.0
- happstack-lite-7.3.6
- lilypond-1.9.0
- monadplus-1.4.2
- music-articulation-1.9.0
- music-dynamics-1.9.0
- music-dynamics-literal-1.9.0
- music-parts-1.9.0
- music-pitch-1.9.0
- music-pitch-literal-1.9.0
- music-preludes-1.9.0
- music-score-1.9.0
- music-suite-1.9.0
- musicxml2-1.9.0
- positive-0.4.1
- prettify-1.0
- reverse-apply-2.0.1
- roman-numerals-0.5.1.5
- transformers-0.4.3.0
- ty-0.1.6
- type-unary-0.2.21
resolver: lts-4.2
